//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7SE2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class admin
    {
        public int id { get; set; }
        [Display(Name = "Full Name")]
        public string full_name { get; set; }
        [Display(Name = "User Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string user_name { get; set; }
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]
        public string password { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
