//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7SE2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image_name { get; set; }
        public Nullable<int> category_id { get; set; }
        public string featured { get; set; }
        public string active { get; set; }
    
        public virtual category category { get; set; }
    }
}
