//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7SE2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string food { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string status { get; set; }
        public string customer_name { get; set; }
        public string customer_contact { get; set; }
        public string customer_email { get; set; }
        public string customer_address { get; set; }
    }
}
