//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7SE2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class order
    {
        public int id { get; set; }
        [Display(Name = "Food Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string food { get; set; }
        [Display(Name = "Order Price")]
        public Nullable<decimal> price { get; set; }
        [Display(Name = "Order Quantity")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> qty { get; set; }
        [Display(Name = "Total Price")]
        public Nullable<decimal> total { get; set; }
        [Display(Name = "Order Date")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<System.DateTime> order_date { get; set; }
        [Display(Name = "Image Path")]
        public string image_name { get; set; }
        [Display(Name = "User Name")]
        public string user_name { get; set; }
    }
}
